---
# Create AH Users
- name: Manage Hub Users Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ hub_configuration_user_secure_logging }}"
  block:
    - name: Add Automation Hub User
      ansible.hub.ah_user:
        username: "{{ __hub_user_item.username | default(omit) }}"
        # new_name:         "{{ __user.new_name | default(omit) }}"  <-- Needs adding once new_name option added to module
        groups: "{{ __hub_user_item.groups | default(omit) }}"
        append: "{{ __hub_user_item.append | default(omit) }}"
        first_name: "{{ __hub_user_item.first_name | default(omit) }}"
        last_name: "{{ __hub_user_item.last_name | default(omit) }}"
        email: "{{ __hub_user_item.email | default(omit) }}"
        is_superuser: "{{ __hub_user_item.is_superuser | default(omit) }}"
        password: "{{ __hub_user_item.password | default(omit) }}"
        state: "{{ __hub_user_item.state | default(hub_state | default(ah_state | default('present'))) }}"
        ah_host: "{{ aap_hostname | default(omit) }}"
        ah_username: "{{ aap_username | default(omit) }}"
        ah_password: "{{ aap_password | default(omit) }}"
        ah_path_prefix: "{{ hub_path_prefix | default(ah_path_prefix | default(omit)) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
        request_timeout: "{{ aap_request_timeout | default(omit) }}"
      loop: "{{ aap_user_accounts }}"
      loop_control:
        loop_var: __hub_user_item
        label: "{{ __operation.verb }} the user {{ __hub_user_item.username }} to Hub"
        pause: "{{ hub_configuration_user_accounts_loop_delay }}"
      async: "{{ hub_configuration_user_async_timeout }}"
      poll: 0
      register: __users_job_async
      changed_when: not __users_job_async.changed
      vars:
        __operation: "{{ operation_translate[__hub_user_item.state | default(platform_state) | default('present')] }}"

    - name: Create User | Wait for finish the user creation
      when:
        - not ansible_check_mode
        - __users_job_async_result_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __users_job_async.results }}"
      loop_control:
        loop_var: __users_job_async_result_item
        label: "{{ __operation.verb }} User {{ __users_job_async_result_item.__hub_user_item.username }} | Wait for finish the User {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ hub_configuration_user_secure_logging }}"
        cas_async_delay: "{{ hub_configuration_user_async_delay }}"
        cas_async_retries: "{{ hub_configuration_user_async_retries }}"
        cas_job_async_results_item: "{{ __users_job_async_result_item }}"
        cas_error_list_var_name: "hub_user_errors"
        __operation: "{{ operation_translate[__users_job_async_result_item.__hub_user_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} User {{ __users_job_async_result_item.__hub_user_item.username }} | Wait for finish the User {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __users_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __users_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __users_job_async.results }}"
      loop_control:
        loop_var: __users_job_async_result_item
        label: "Cleaning up job results file: {{ __users_job_async_result_item.results_file | default('Unknown') }}"
...
