---
- name: Manage Credential Types Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ controller_configuration_credential_types_secure_logging }}"
  block:
    - name: Managing Credential Types
      ansible.controller.credential_type:
        name: "{{ __controller_credential_type_item.name | mandatory }}"
        new_name: "{{ __controller_credential_type_item.new_name | default(omit, true) }}"
        description: "{{ __controller_credential_type_item.description | default(('' if controller_configuration_credential_types_enforce_defaults else omit), true) }}"
        injectors: "{{ __controller_credential_type_item.injectors | default(({} if controller_configuration_credential_types_enforce_defaults else omit), true) | regex_replace('{  {', '{_~~remove~~_{') | regex_replace('_~~remove~~_', '') }}"
        inputs: "{{ __controller_credential_type_item.inputs | default(({} if controller_configuration_credential_types_enforce_defaults else omit), true) }}"
        kind: "{{ __controller_credential_type_item.kind | default('cloud') }}"
        state: "{{ __controller_credential_type_item.state | default(platform_state | default('present')) }}"

        # Role specific options
        controller_username: "{{ aap_username | default(omit, true) }}"
        controller_password: "{{ aap_password | default(omit, true) }}"
        controller_oauthtoken: "{{ aap_token | default(omit, true) }}"
        request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
        controller_host: "{{ aap_hostname | default(omit, true) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
      loop: "{{ credential_types if credential_types is defined else controller_credential_types }}"
      loop_control:
        loop_var: __controller_credential_type_item
        label: "{{ __operation.verb }} Credential Type {{ __controller_credential_type_item.name }}"
        pause: "{{ controller_configuration_credential_types_loop_delay }}"
      async: "{{ ansible_check_mode | ternary(0, 1000) }}"
      poll: 0
      register: __credentialtypes_job_async
      changed_when: (__credentialtypes_job_async.changed if ansible_check_mode else false)
      vars:
        __operation: "{{ operation_translate[__controller_credential_type_item.state | default(platform_state) | default('present')] }}"

    - name: Flag for errors (check mode only)
      ansible.builtin.set_fact:
        error_flag: true
      when: ansible_check_mode and __credentialtypes_job_async.failed is defined and __credentialtypes_job_async.failed

    - name: Managing Controller Credential Types | Wait for finish the credential types management
      when:
        - not ansible_check_mode
        - __credentialtypes_job_async_result_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __credentialtypes_job_async.results }}"
      loop_control:
        loop_var: __credentialtypes_job_async_result_item
        label: "{{ __operation.verb }} Controller Credential Type {{ __credentialtypes_job_async_result_item.__controller_credential_type_item.name }} | Wait for finish the credential type {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ controller_configuration_credential_types_secure_logging }}"
        cas_async_delay: "{{ controller_configuration_credential_types_async_delay }}"
        cas_async_retries: "{{ controller_configuration_credential_types_async_retries }}"
        cas_job_async_results_item: "{{ __credentialtypes_job_async_result_item }}"
        cas_error_list_var_name: "controller_credential_types_errors"
        __operation: "{{ operation_translate[__credentialtypes_job_async_result_item.__controller_credential_type_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} Controller Credential Type {{ __credentialtypes_job_async_result_item.__controller_credential_type_item.name }} | Wait for finish the credential type {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __credentialtypes_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __credentialtypes_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __credentialtypes_job_async.results }}"
      loop_control:
        loop_var: __credentialtypes_job_async_result_item
        label: "Cleaning up job results file: {{ __credentialtypes_job_async_result_item.results_file | default('Unknown') }}"
...
