---
- name: Manage Controller Teams Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ controller_configuration_platform_teams_secure_logging }}"
  block:
    - name: Managing Ansible Controller Teams
      ansible.controller.team:
        name: "{{ __controller_team_item.name | mandatory }}"
        new_name: "{{ __controller_team_item.new_name | default(omit, true) }}"
        description: "{{ __controller_team_item.description | default(('' if controller_configuration_platform_teams_enforce_defaults else omit), true) }}"
        organization: "{{ __controller_team_item.organization.name | default(__controller_team_item.organization) | mandatory }}"
        state: "{{ __controller_team_item.state | default(platform_state | default('present')) }}"

        # Role Standard Options
        controller_host: "{{ aap_hostname | default(omit, true) }}"
        controller_password: "{{ aap_password | default(omit, true) }}"
        controller_username: "{{ aap_username | default(omit, true) }}"
        controller_oauthtoken: "{{ aap_token | default(omit, true) }}"
        request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
      loop: "{{ aap_teams }}"
      loop_control:
        loop_var: __controller_team_item
        label: "{{ __operation.verb }} Ansible Controller Team {{ __controller_team_item.name }}"
        pause: "{{ controller_configuration_teams_loop_delay }}"
      async: "{{ ansible_check_mode | ternary(0, 1000) }}"
      poll: 0
      register: __controller_team_job_async
      changed_when: (__controller_team_job_async.changed if ansible_check_mode else false)
      vars:
        __operation: "{{ operation_translate[__controller_team_item.state | default(platform_state) | default('present')] }}"

    - name: Flag for errors (check mode only)
      ansible.builtin.set_fact:
        error_flag: true
      when: ansible_check_mode and __controller_team_job_async.failed is defined and __controller_team_job_async.failed

    - name: Managing Teams | Wait for finish the Teams management
      when:
        - not ansible_check_mode
        - __controller_team_job_async_results_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __controller_team_job_async.results }}"
      loop_control:
        loop_var: __controller_team_job_async_results_item
        label: "{{ __operation.verb }} Teams | Wait for finish the Teams {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ controller_configuration_platform_teams_secure_logging }}"
        cas_async_delay: "{{ controller_configuration_platform_teams_async_delay }}"
        cas_async_retries: "{{ controller_configuration_platform_teams_async_retries }}"
        cas_job_async_results_item: "{{ __controller_team_job_async_results_item }}"
        cas_error_list_var_name: "controller_teams_errors"
        __operation: "{{ operation_translate[__controller_team_job_asycn_results_item.__controller_team_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} Teams | Wait for finish the Teams {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __controller_team_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __controller_team_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __controller_team_job_async.results }}"
      loop_control:
        loop_var: __controller_team_job_async_results_item
        label: "Cleaning up job results file: {{ __controller_team_job_async_results_item.results_file | default('Unknown') }}"
...
