---
- name: Sort out vars that are included
  ansible.builtin.include_tasks: include_wildcard_vars.yml
  when: dispatch_include_wildcard_vars

- name: "Run the following infra.aap_configuration roles: {{ aap_configuration_dispatcher_roles | map(attribute='role') | join(', ') }}"
  ansible.builtin.include_role:
    name: "{{ __role.role }}"
    apply:
      tags: "{{ __role.tags }}"
  when: vars[__role.var] is defined
  tags: always
  loop: "{{ aap_configuration_dispatcher_roles }}"
  loop_control:
    loop_var: __role
  vars:
    assign_galaxy_credentials_to_org: "{{ __role.assign_galaxy_credentials_to_org | default(false) }}"
    assign_default_ee_to_org: "{{ __role.assign_default_ee_to_org | default(false) }}"
    assign_notification_templates_to_org: "{{ __role.assign_notification_templates_to_org | default(false) }}"
    assign_instance_groups_to_org: "{{ __role.assign_instance_groups_to_org | default(false) }}"

- name: Display errors and fail
  when:
    - aap_configuration_role_errors is defined
    - aap_configuration_role_errors is mapping
    - aap_configuration_role_errors | dict2items | selectattr('value', 'ne', []) | list | length > 0
  ansible.builtin.debug:
    msg:
      - "Errors encountered applying configurations:"
      - "{{ aap_configuration_role_errors }}"
  failed_when: aap_configuration_role_errors | dict2items | selectattr('value', 'ne', []) | list | length > 0

- name: Fail the playbook if there were errors (check mode only)
  ansible.builtin.fail:
    msg: The execution has failed because of errors (probably due to missing dependencies caused by check mode).
  when: ansible_check_mode and error_flag is defined and error_flag
...
