- name: Prepare release playbook
  hosts: localhost
  vars:
    collection_name: ansible.hub
    version: 1.0.3
  tasks:
    - name: Generate next release version
      when: version is not defined
      block:
        - name: Get the next release version # noqa command-instead-of-module no-changed-when
          ansible.builtin.shell: set -o pipefail; git tag --sort=-creatordate --merged|head -n1|perl -pe 's/(\d+\.)(\d+)\.\d+/"$1" . ($2+1) . ".0"/e'
          register: result

        - name: Set the release version
          ansible.builtin.set_fact:
            version: "{{ result.stdout }}"

    - name: Install antsibull-docs and antsibull-changelog
      ansible.builtin.pip:
        name:
          - antsibull-docs
          - antsibull-changelog

    - name: Create release branch # noqa command-instead-of-module no-changed-when
      ansible.builtin.command: git checkout -b "prepare_{{ version }}_release"

    - name: Update galaxy.yml, docs, changelog and cleanup
      block:
        - name: Update galaxy.yml
          ansible.builtin.lineinfile:
            path: "{{ playbook_dir }}/../galaxy.yml"
            regexp: "^version: "
            line: "version: {{ version }}"

        - name: Update documentation # noqa no-changed-when
          ansible.builtin.command: 'antsibull-docs collection-plugins {{ collection_name }} --dest-dir {{ playbook_dir }}/../docs --use-current --output-format simplified-rst --fqcn-plugin-names' # noqa yaml[line-length]

        - name: Refresh the changelog # noqa no-changed-when
          ansible.builtin.command: 'antsibull-changelog release --verbose --version {{ version }}'

        - name: Find the yaml file
          ansible.builtin.find:
            paths: "{{ playbook_dir }}/../changelogs/fragments"
            excludes: ".gitkeep,"
          register: files_to_delete

        - name: Clean up the changelog fragments
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: absent
          with_items: "{{ files_to_delete.files }}"

        - name: Add everything # noqa command-instead-of-module no-changed-when
          ansible.builtin.command: git add --all

        # git diff-index --quiet HEAD
        #   0 -> repository is clean, nothing to commit
        #   1 -> the opposite
        - name: Commit everything # noqa command-instead-of-module no-changed-when
          ansible.builtin.shell: 'git diff-index --quiet HEAD || git commit -m "prepare {{ version }} release"'

      rescue:
        - name: Print debug message
          ansible.builtin.debug:
            msg: "Failed to release {{ version }}. Git source is dirty, perform 'git branch -D prepare_{{ version }}_release' before running this playbook."