---
# Create Controller applications
- name: Manage Controller Applications Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ controller_configuration_applications_secure_logging }}"
  block:
    - name: Managing Controller Applications
      ansible.controller.application:
        name: "{{ __application_item.name | mandatory }}"
        new_name: "{{ __application_item.new_name | default(omit, true) }}"
        organization: "{{ __application_item.organization | mandatory }}"
        description: "{{ __application_item.description | default(('' if controller_configuration_applications_enforce_defaults else omit), true) }}"
        authorization_grant_type: "{{ __application_item.authorization_grant_type | default('password') }}"
        client_type: "{{ __application_item.client_type | default('public') }}"
        redirect_uris: "{{ __application_item.redirect_uris | default([]) }}"
        skip_authorization: "{{ __application_item.skip_authorization | default((false if controller_configuration_applications_enforce_defaults else omit), true) }}"
        state: "{{ __application_item.state | default(platform_state | default('present')) }}"

        # Role specific options
        controller_username: "{{ aap_username | default(omit, true) }}"
        controller_password: "{{ aap_password | default(omit, true) }}"
        controller_oauthtoken: "{{ aap_token | default(omit, true) }}"
        request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
        controller_host: "{{ aap_hostname | default(omit, true) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
      loop: "{{ aap_applications }}"
      loop_control:
        loop_var: __application_item
        label: "{{ __operation.verb }} Controller Application {{ __application_item.name }}"
        pause: "{{ controller_configuration_applications_loop_delay }}"
      async: "{{ ansible_check_mode | ternary(0, 1000) }}"
      poll: 0
      register: __applications_job_async
      changed_when: (__applications_job_async.changed if ansible_check_mode else false)
      vars:
        __operation: "{{ operation_translate[__application_item.state | default(platform_state) | default('present')] }}"

    - name: Flag for errors (check mode only)
      ansible.builtin.set_fact:
        error_flag: true
      when: ansible_check_mode and __applications_job_async.failed is defined and __applications_job_async.failed

    - name: Managing Controller Applications | Wait for finish the Application management
      when:
        - not ansible_check_mode
        - __applications_job_async_results_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __applications_job_async.results }}"
      loop_control:
        loop_var: __applications_job_async_results_item
        label: "{{ __operation.verb }} Controller Application {{ __applications_job_async_results_item.__application_item.name }} | Wait for finish the Application {{
          __operation.action }}"
      vars:
        cas_secure_logging: "{{ controller_configuration_applications_secure_logging }}"
        cas_async_delay: "{{ controller_configuration_applications_async_delay }}"
        cas_async_retries: "{{ controller_configuration_applications_async_retries }}"
        cas_job_async_results_item: "{{ __applications_job_async_results_item }}"
        cas_error_list_var_name: "controller_applications_errors"
        __operation: "{{ operation_translate[__applications_job_async_results_item.__application_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} Controller Application {{ __applications_job_async_results_item.__application_item.name }} | Wait for finish the Application {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __applications_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __applications_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __applications_job_async.results }}"
      loop_control:
        loop_var: __applications_job_async_results_item
        label: "Cleaning up job results file: {{ __applications_job_async_results_item.results_file | default('Unknown') }}"
...
