---
# Create AH repository
- name: Manage Hub Collection Remote Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ hub_configuration_collection_remote_secure_logging }}"
  block:
    - name: Add Automation Hub Collection Remote repository
      ansible.hub.collection_remote:
        name: "{{ __hub_collection_remote_item.name }}"
        url: "{{ __hub_collection_remote_item.url }}"
        auth_url: "{{ __hub_collection_remote_item.auth_url | default(omit) }}"
        token: "{{ __hub_collection_remote_item.token | default(omit) }}"
        policy: "{{ __hub_collection_remote_item.policy | default(omit) }}"
        requirements: "{{ __hub_collection_remote_item.requirements | default(omit) }}"
        requirements_file: "{{ __hub_collection_remote_item.requirements_file | default(omit) }}"
        username: "{{ __hub_collection_remote_item.username | default(omit) }}"
        password: "{{ __hub_collection_remote_item.password | default(omit) }}"
        tls_validation: "{{ __hub_collection_remote_item.tls_validation | default(true) }}"
        client_key: "{{ __hub_collection_remote_item.client_key | default(omit) }}"
        client_cert: "{{ __hub_collection_remote_item.client_cert | default(omit) }}"
        ca_cert: "{{ __hub_collection_remote_item.ca_cert | default(omit) }}"
        client_key_path: "{{ __hub_collection_remote_item.client_key_path | default(omit) }}"
        client_cert_path: "{{ __hub_collection_remote_item.client_cert_path | default(omit) }}"
        ca_cert_path: "{{ __hub_collection_remote_item.ca_cert_path | default(omit) }}"
        download_concurrency: "{{ __hub_collection_remote_item.download_concurrency | default(10) }}"
        max_retries: "{{ __hub_collection_remote_item.max_retries | default(0) }}"
        rate_limit: "{{ __hub_collection_remote_item.rate_limit | default(8) }}"
        signed_only: "{{ __hub_collection_remote_item.signed_only | default(omit) }}"
        sync_dependencies: "{{ __hub_collection_remote_item.sync_dependencies | default(omit) }}"
        proxy_url: "{{ __hub_collection_remote_item.proxy_url | default(proxy_url | default(omit)) }}"
        proxy_username: "{{ __hub_collection_remote_item.proxy_username | default(proxy_username | default(omit)) }}"
        proxy_password: "{{ __hub_collection_remote_item.proxy_password | default(proxy_password | default(omit)) }}"
        state: "{{ __hub_collection_remote_item.state | default(hub_state | default(ah_state | default('present'))) }}"
        ah_host: "{{ aap_hostname | default(omit) }}"
        ah_username: "{{ aap_username | default(omit) }}"
        ah_password: "{{ aap_password | default(omit) }}"
        ah_path_prefix: "{{ hub_path_prefix | default(ah_path_prefix | default(omit)) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
        request_timeout: "{{ aap_request_timeout | default(omit) }}"
      loop: "{{ hub_collection_remotes }}"
      loop_control:
        loop_var: __hub_collection_remote_item
        label: "{{ __operation.verb }} the collection remote {{ __hub_collection_remote_item.name }} in Hub"
        pause: "{{ hub_configuration_collection_remote_loop_delay }}"
      async: "{{ hub_configuration_collection_remote_async_timeout }}"
      poll: 0
      register: __collection_remote_job_async
      changed_when: not __collection_remote_job_async.changed
      vars:
        __operation: "{{ operation_translate[__hub_collection_remote_item.state | default(platform_state) | default('present')] }}"

    - name: Create Repository | Wait for finish the repository creation
      when:
        - not ansible_check_mode
        - __collection_remote_job_async_result_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __collection_remote_job_async.results }}"
      loop_control:
        loop_var: __collection_remote_job_async_result_item
        label: "{{ __operation.verb }} Collection remote {{ __collection_remote_job_async_result_item.__hub_collection_remote_item.name }} | Wait for finish the Collection
          remote {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ hub_configuration_collection_remote_secure_logging }}"
        cas_async_delay: "{{ hub_configuration_collection_remote_async_delay }}"
        cas_async_retries: "{{ hub_configuration_collection_remote_async_retries }}"
        cas_job_async_results_item: "{{ __collection_remote_job_async_result_item }}"
        cas_error_list_var_name: "hub_collection_remote_errors"
        __operation: "{{ operation_translate[__collection_remote_job_async_result_item.__hub_collection_remote_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} Collection remote {{ __collection_remote_job_async_result_item.__hub_collection_remote_item.name }} | Wait for finish the Collection remote {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __collection_remote_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __collection_remote_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __collection_remote_job_async.results }}"
      loop_control:
        loop_var: __collection_remote_job_async_result_item
        label: "Cleaning up job results file: {{ __collection_remote_job_async_result_item.results_file | default('Unknown') }}"
...
