---
- name: async_gateway_team | An async_gateway_team block
  block:
    - name: async_gateway_team | Managing team | Wait for finish the team operation
      ansible.builtin.async_status:
        jid: "{{ __gateway_teams_job_async_results_item.ansible_job_id }}"
      register: __gateway_teams_job_async_result
      until: __gateway_teams_job_async_result.finished
      retries: "{{ gateway_teams_async_retries }}"
      delay: "{{ gateway_teams_async_delay }}"
  rescue:
    - name: async_gateway_team | Load error details
      ansible.builtin.include_vars:
        file: "{{ __gateway_teams_job_async_result.results_file | default('Unknown') }}"
        name: __error_data

    - name: async_gateway_team | Show error and stop execution
      when: not aap_configuration_collect_logs
      ansible.builtin.fail:
        msg: "error: {{ __error_data['msg'] }}, response: {{ __error_data['response'] | default ('N/A') }}"

    - name: async_gateway_team | Building list of not processed team
      ansible.builtin.set_fact:
        __gateway_team_error_list: "{{ __gateway_teams_error_list | default([]) + [
                                                                                  {
                                                                                   'name': __error_data['invocation']['module_args']['name'] | default(''),
                                                                                   'error': __error_data['msg'] | default('')
                                                                                  }
                                                                                 ]
                                         }}"
...
