---
# Create AH EE repository
- name: Manage Hub EE Repository Sync Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ hub_configuration_ee_repository_secure_logging }}"
  block:
    - name: Sync Automation Hub EE Repository
      ansible.hub.ah_ee_repository_sync:
        name: "{{ __hub_ee_repository_sync_item.name }}"
        wait: "{{ __hub_ee_repository_sync_item.wait | default(omit) }}"
        interval: "{{ __hub_ee_repository_sync_item.interval | default(hub_configuration_ee_repository_sync_async_delay) }}"
        timeout: "{{ __hub_ee_repository_sync_item.timeout | default(omit) }}"
        ah_host: "{{ aap_hostname | default(omit) }}"
        ah_username: "{{ aap_username | default(omit) }}"
        ah_password: "{{ aap_password | default(omit) }}"
        ah_path_prefix: "{{ hub_path_prefix | default(ah_path_prefix | default(omit)) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
        request_timeout: "{{ aap_request_timeout | default(omit) }}"
      loop: "{{ hub_ee_repositories }}"
      loop_control:
        loop_var: __hub_ee_repository_sync_item
        label: "{{ __operation.verb }} the EE repository sync {{ __hub_ee_repository_sync_item.name }} in Hub"
        pause: "{{ hub_configuration_ee_repository_sync_loop_delay }}"
      when: __hub_ee_repository_sync_item.sync | default(false)
      async: "{{ hub_configuration_ee_repository_sync_async_timeout }}"
      poll: 0
      register: __ee_repository_syncs_job_async
      changed_when: not __ee_repository_syncs_job_async.changed
      vars:
        __operation: "{{ operation_translate[__hub_ee_repository_sync_item.state | default(platform_state) | default('present')] }}"

    - name: EE Repository Sync | Wait for finish the ee_repository_sync to finish
      when:
        - not ansible_check_mode
        - __ee_repository_syncs_job_async_result_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __ee_repository_syncs_job_async.results }}"
      loop_control:
        loop_var: __ee_repository_syncs_job_async_result_item
        label: "{{ __operation.verb }} EE repository sync {{ __ee_repository_syncs_job_async_result_item.__hub_ee_repository_sync_item.name }} | Wait for finish the EE repository sync {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ hub_configuration_ee_repository_secure_logging }}"
        cas_async_delay: "{{ hub_configuration_ee_repository_sync_async_delay }}"
        cas_async_retries: "{{ hub_configuration_ee_repository_sync_async_retries }}"
        cas_job_async_results_item: "{{ __ee_repository_syncs_job_async_result_item }}"
        cas_error_list_var_name: "hub_ee_repository_sync_errors"
        __operation: "{{ operation_translate[__ee_repository_syncs_job_async_result_item.__hub_ee_repository_sync_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} EE repository sync {{ __ee_repository_syncs_job_async_result_item.__hub_ee_repository_sync_item.name }} | Wait for finish the EE repository sync {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __ee_repository_syncs_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __ee_repository_syncs_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __ee_repository_syncs_job_async.results }}"
      loop_control:
        loop_var: __ee_repository_syncs_job_async_result_item
        label: "Cleaning up job results file: {{ __ee_repository_syncs_job_async_result_item.results_file | default('Unknown') }}"
...
