---
# Create AH Group
- name: Manage Hub Group Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ hub_configuration_group_secure_logging }}"
  block:
    - name: Add Automation Hub group
      ansible.hub.ah_group:
        name: "{{ __hub_group_item.name | default(omit) }}"
        # new_name:         "{{ __group.new_name | default(omit) }}"  <-- Needs adding once new_name option added to module
        state: "{{ __hub_group_item.state | default(hub_state | default(ah_state | default('present'))) }}"
        ah_host: "{{ aap_hostname | default(omit) }}"
        ah_username: "{{ aap_username | default(omit) }}"
        ah_password: "{{ aap_password | default(omit) }}"
        ah_path_prefix: "{{ hub_path_prefix | default(ah_path_prefix | default(omit)) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
        request_timeout: "{{ aap_request_timeout | default(omit) }}"
      loop: "{{ aap_teams }}"
      loop_control:
        loop_var: __hub_group_item
        label: "{{ __operation.verb }} the group {{ __hub_group_item.name }} in Hub"
        pause: "{{ hub_configuration_group_loop_delay }}"
      async: "{{ hub_configuration_group_async_timeout }}"
      poll: 0
      register: __groups_job_async
      changed_when: not __groups_job_async.changed
      vars:
        __operation: "{{ operation_translate[__hub_group_item.state | default(platform_state) | default('present')] }}"

    - name: Create Group | Wait for finish the group creation
      when:
        - not ansible_check_mode
        - __groups_job_async_result_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __groups_job_async.results }}"
      loop_control:
        loop_var: __groups_job_async_result_item
        label: "{{ __operation.verb }} Group {{ __groups_job_async_result_item.__hub_group_item.name }} | Wait for finish the Group {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ hub_configuration_group_secure_logging }}"
        cas_async_delay: "{{ hub_configuration_group_async_delay }}"
        cas_async_retries: "{{ hub_configuration_group_async_retries }}"
        cas_job_async_results_item: "{{ __groups_job_async_result_item }}"
        cas_error_list_var_name: "hub_group_errors"
        __operation: "{{ operation_translate[__groups_job_async_result_item.__hub_group_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} Group {{ __groups_job_async_result_item.__hub_group_item.name }} | Wait for finish the Group {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __groups_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __groups_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __groups_job_async.results }}"
      loop_control:
        loop_var: __groups_job_async_result_item
        label: "Cleaning up job results file: {{ __groups_job_async_result_item.results_file | default('Unknown') }}"
...
