---
# Create EDA Controller Credential
- name: Manage EDA Controller credential Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ eda_configuration_credentials_secure_logging }}"
  block:
    - name: Add EDA Controller credential
      ansible.eda.credential:
        name: "{{ __credential_item.name }}"
        new_name: "{{ __credential_item.new_name | default(omit) }}"
        description: "{{ __credential_item.description | default(omit) }}"
        organization_name: "{{ __credential_item.organization | default(omit) }}"
        credential_type_name: "{{ __credential_item.credential_type | mandatory }}"
        inputs: "{{ __credential_item.inputs | default(omit) }}"
        state: "{{ __credential_item.state | default(eda_state | default('present')) }}"
        controller_host: "{{ aap_hostname | default(omit, true) }}"
        controller_username: "{{ aap_username | default(omit, true) }}"
        controller_password: "{{ aap_password | default(omit, true) }}"
        controller_token: "{{ aap_token | default(omit, true) }}"
        request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
      loop: "{{ eda_credentials }}"
      loop_control:
        loop_var: __credential_item
        label: "{{ __operation.verb }} the credential {{ __credential_item.name }} to EDA"
        pause: "{{ eda_configuration_credentials_async_delay }}"
      async: 1000
      poll: 0
      register: __credentials_job_async
      changed_when: not __credentials_job_async.changed
      vars:
        __operation: "{{ operation_translate[__credentials_job_async.state | default(platform_state) | default('present')] }}"

    - name: Create credential | Wait for finish the credential creation
      when:
        - not ansible_check_mode
        - __credentials_job_async_result_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __credentials_job_async.results }}"
      loop_control:
        loop_var: __credentials_job_async_result_item
        label: "{{ __operation.verb }} credential {{ __credentials_job_async_result_item.__credential_item.name }} | Wait for finish the credential {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ eda_configuration_credentials_secure_logging }}"
        cas_async_delay: "{{ eda_configuration_credentials_async_delay }}"
        cas_async_retries: "{{ eda_configuration_credentials_async_retries }}"
        cas_job_async_results_item: "{{ __credentials_job_async_result_item }}"
        cas_error_list_var_name: "eda_credentials_errors"
        __operation: "{{ operation_translate[__credentials_job_async_result_item.__credential_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} credential {{ __credentials_job_async_result_item.__credential_item.name }} | Wait for finish the credential {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __credentials_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __credentials_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __credentials_job_async.results }}"
      loop_control:
        loop_var: __credentials_job_async_result_item
        label: "Cleaning up job results file: {{ __credentials_job_async_result_item.results_file | default('Unknown') }}"
...
