---
# Create AH EE Image
- name: Manage Hub EE Image Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ hub_configuration_ee_image_secure_logging }}"
  block:
    - name: Add Automation Hub EE Image
      ansible.hub.ah_ee_image:
        name: "{{ __ee_image_item.name }}"
        # new_name:         "{{ __ee_image_item.new_name | default(omit) }}"  <-- Needs adding once new_name option added to module
        append: "{{ __ee_image_item.append | default(omit) }}"
        tags: "{{ __ee_image_item.tags | default(omit) }}"
        state: "{{ __ee_image_item.state | default(hub_state | default(ah_state | default('present'))) }}"
        ah_host: "{{ aap_hostname | default(omit) }}"
        ah_username: "{{ aap_username | default(omit) }}"
        ah_password: "{{ aap_password | default(omit) }}"
        ah_path_prefix: "{{ hub_path_prefix | default(ah_path_prefix | default(omit)) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
        request_timeout: "{{ aap_request_timeout | default(omit) }}"
      loop: "{{ hub_ee_images }}"
      loop_control:
        loop_var: __ee_image_item
        label: "{{ __operation.verb }} the EE image {{ __ee_image_item.name }} in Hub"
        pause: "{{ hub_configuration_ee_image_loop_delay }}"
      async: "{{ hub_configuration_ee_image_async_timeout }}"
      poll: 0
      register: __ee_images_job_async
      changed_when: not __ee_images_job_async.changed
      vars:
        __operation: "{{ operation_translate[__ee_image_item.state | default(platform_state) | default('present')] }}"

    - name: Create EE Image | Wait for finish the ee_image creation
      when:
        - not ansible_check_mode
        - __ee_images_job_async_result_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __ee_images_job_async.results }}"
      loop_control:
        loop_var: __ee_images_job_async_result_item
        label: "{{ __operation.verb }} EE Image {{ __ee_images_job_async_result_item.__ee_image_item.name }} | Wait for finish the EE image {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ hub_configuration_ee_image_secure_logging }}"
        cas_async_delay: "{{ hub_configuration_ee_image_async_delay }}"
        cas_async_retries: "{{ hub_configuration_ee_image_async_retries }}"
        cas_job_async_results_item: "{{ __ee_images_job_async_result_item }}"
        cas_error_list_var_name: "hub_ee_image_errors"
        __operation: "{{ operation_translate[__ee_images_job_async_result_item.__ee_image_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} EE Image {{ __ee_images_job_async_result_item.__ee_image_item.name }} | Wait for finish the EE image {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __ee_images_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __ee_images_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __ee_images_job_async.results }}"
      loop_control:
        loop_var: __ee_images_job_async_result_item
        label: "Cleaning up job results file: {{ __ee_images_job_async_result_item.results_file | default('Unknown') }}"
...
