---
# Create AH Role
- name: Manage Hub Roles Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ hub_configuration_role_secure_logging }}"
  block:
    - name: Add Automation Hub role
      ansible.hub.ah_role:
        name: "{{ __hub_role_item.name }}"
        description: "{{ __hub_role_item.description | default(omit) }}"
        perms: "{{ __hub_role_item.perms | default(omit) }}"
        state: "{{ __hub_role_item.state | default(hub_state | default(ah_state | default('present'))) }}"
        ah_host: "{{ aap_hostname | default(omit) }}"
        ah_username: "{{ aap_username | default(omit) }}"
        ah_password: "{{ aap_password | default(omit) }}"
        ah_path_prefix: "{{ hub_path_prefix | default(ah_path_prefix | default(omit)) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
        request_timeout: "{{ aap_request_timeout | default(omit) }}"
      loop: "{{ hub_roles }}"
      loop_control:
        loop_var: __hub_role_item
        label: "{{ __operation.verb }} the Role {{ __hub_role_item.name }} to Hub"
        pause: "{{ hub_configuration_role_loop_delay }}"
      async: "{{ hub_configuration_role_async_timeout }}"
      poll: 0
      register: __roles_job_async
      changed_when: not __roles_job_async.changed
      vars:
        __operation: "{{ operation_translate[__hub_role_item.state | default(platform_state) | default('present')] }}"

    - name: Create Role | Wait for finish the role creation
      when:
        - not ansible_check_mode
        - __roles_job_async_result_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __roles_job_async.results }}"
      loop_control:
        loop_var: __roles_job_async_result_item
        label: "{{ __operation.verb }} Role {{ __roles_job_async_result_item.__hub_role_item.name }} | Wait for finish the Role {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ hub_configuration_role_secure_logging }}"
        cas_async_delay: "{{ hub_configuration_role_async_delay }}"
        cas_async_retries: "{{ hub_configuration_role_async_retries }}"
        cas_job_async_results_item: "{{ __roles_job_async_result_item }}"
        cas_error_list_var_name: "hub_role_errors"
        __operation: "{{ operation_translate[__roles_job_async_result_item.__hub_role_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} Role {{ __roles_job_async_result_item.__hub_role_item.name }} | Wait for finish the Role {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __roles_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __roles_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __roles_job_async.results }}"
      loop_control:
        loop_var: __roles_job_async_result_item
        label: "Cleaning up job results file: {{ __roles_job_async_result_item.results_file | default('Unknown') }}"
...
