---
- name: Manage Gateway HTTP Ports Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ gateway_http_ports_secure_logging }}"
  block:
    - name: HTTP Ports | Configuration
      ansible.platform.http_port:
        name: "{{ __gateway_http_ports_item.name | mandatory }}"
        new_name: "{{ __gateway_http_ports_item.new_name | default(omit) }}"
        number: "{{ __gateway_http_ports_item.number | default(omit) }}"
        use_https: "{{ __gateway_http_ports_item.use_https | default(false) }}"
        is_api_port: "{{ __gateway_http_ports_item.is_api_port | default(false) }}"
        state: "{{ __gateway_http_ports_item.state | default(platform_state | default(omit, true)) }}"

        # Role Standard Options
        gateway_hostname: "{{ aap_hostname | default(omit, true) }}"
        gateway_username: "{{ aap_username | default(omit, true) }}"
        gateway_password: "{{ aap_password | default(omit, true) }}"
        gateway_token: "{{ aap_token | default(omit, true) }}"
        gateway_request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
        gateway_validate_certs: "{{ aap_validate_certs | default(omit) }}"
      loop: "{{ gateway_http_ports }}"
      loop_control:
        loop_var: __gateway_http_ports_item
        label: "{{ __operation.verb }} AAP Platform Http Ports {{ __gateway_http_ports_item.name }}"
        pause: "{{ gateway_http_ports_loop_delay }}"
      async: 1000
      poll: 0
      register: __gateway_http_ports_job_async
      changed_when: not __gateway_http_ports_job_async.changed
      vars:
        __operation: "{{ operation_translate[__gateway_http_ports_item.state | default(platform_state) | default('present')] }}"

    - name: Http Ports | Wait for finish the configuration
      when:
        - not ansible_check_mode
        - __gateway_http_ports_job_async_results_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __gateway_http_ports_job_async.results }}"
      loop_control:
        loop_var: __gateway_http_ports_job_async_results_item
        label: "{{ __operation.verb }} AAP Platform Http Ports {{ __gateway_http_ports_job_async_results_item.__gateway_http_ports_item.name }} | Wait for finish the
          Http Ports {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ gateway_http_ports_secure_logging }}"
        cas_async_delay: "{{ gateway_http_ports_async_delay }}"
        cas_async_retries: "{{ gateway_http_ports_async_retries }}"
        cas_job_async_results_item: "{{ __gateway_http_ports_job_async_results_item }}"
        cas_error_list_var_name: "gateway_http_ports_errors"
        __operation: "{{ operation_translate[__gateway_http_ports_job_async_results_item.__gateway_http_ports_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} AAP Platform Http Ports {{ __gateway_http_ports_job_async_results_item.__gateway_http_ports_item.name }} | Wait for finish the Http Ports {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __gateway_http_ports_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __gateway_http_ports_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __gateway_http_ports_job_async.results }}"
      loop_control:
        loop_var: __gateway_http_ports_job_async_results_item
        label: "Cleaning up job results file: {{ __gateway_http_ports_job_async_results_item.results_file | default('Unknown') }}"
...
