---
- name: add_workflows_schema | Manage Controller Workflow Nodes Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ controller_configuration_workflow_job_templates_secure_logging }}"
  block:
    # Creating Workflow Node
    - name: add_workflows_schema | Create the Workflow Nodes
      ansible.controller.workflow_job_template_node:
        identifier: "{{ __workflow_loop_node_item.identifier | mandatory }}" # internal identification ID
        extra_data: "{{ __workflow_loop_node_item.extra_data | default(omit, true) }}"
        inventory: "{{ __workflow_loop_node_item.inventory | default(omit, true) }}"
        scm_branch: "{{ __workflow_loop_node_item.scm_branch | default(omit, true) }}"
        job_type: "{{ __workflow_loop_node_item.job_type | default(omit, true) }}"
        job_tags: "{{ __workflow_loop_node_item.job_tags | default(omit, true) }}"
        skip_tags: "{{ __workflow_loop_node_item.skip_tags | default(omit, true) }}"
        limit: "{{ __workflow_loop_node_item.limit | default(omit, true) }}"
        diff_mode: "{{ __workflow_loop_node_item.diff_mode | default(omit) }}"
        verbosity: "{{ __workflow_loop_node_item.verbosity | default(omit, true) }}"
        credentials: "{{ __workflow_loop_node_item.credentials | default(__workflow_loop_node_item.related.credentials | default([]) | map(attribute='name') | list) | default(omit, true) }}"
        workflow_job_template: "{{ __workflow_loop_node_item.workflow_job_template.name | default(__workflow_loop_node_item.workflow_job_template | default(omit, true)) }}"
        unified_job_template: "{{ __workflow_loop_node_item.unified_job_template.name | default(__workflow_loop_node_item.unified_job_template | default(omit, true)) }}" # Run Job template
        lookup_organization: "{{ __workflow_loop_node_item.lookup_organization | default(omit, true) }}"
        execution_environment: "{{ __workflow_loop_node_item.execution_environment.name | default(__workflow_loop_node_item.execution_environment | default(omit, true)) }}"
        forks: "{{ __workflow_loop_node_item.forks | default(omit, true) }}"
        instance_groups: "{{ __workflow_loop_node_item.instance_groups | default(omit, true) }}"
        job_slice_count: "{{ __workflow_loop_node_item.job_slice_count | default(omit, true) }}"
        labels: "{{ __workflow_loop_node_item.labels | default(__workflow_loop_node_item.related.labels | default([]) | map(attribute='name') | list if __workflow_loop_node_item.related.labels is defined else omit) }}"
        timeout: "{{ __workflow_loop_node_item.timeout | default(omit, true) }}"
        approval_node: "{{ __workflow_loop_node_item.approval_node | default(omit, true) }}"
        workflow: "{{ __workflow_loop_item.name | mandatory }}" # Workflow job template name to associate with
        state: "{{ __workflow_loop_node_item.state | default(platform_state | default('present')) }}"
        all_parents_must_converge: "{{ __workflow_loop_node_item.all_parents_must_converge | default('false') }}"
        organization: "{{ __workflow_loop_item.organization.name | default(__workflow_loop_item.organization) }}" # Workflow job template organization

        # Role Standard Options
        controller_username: "{{ aap_username | default(omit, true) }}"
        controller_password: "{{ aap_password | default(omit, true) }}"
        controller_oauthtoken: "{{ aap_token | default(omit, true) }}"
        request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
        controller_host: "{{ aap_hostname | default(omit, true) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
      loop: "{{ __workflow_loop_item.simplified_workflow_nodes }}"
      loop_control:
        loop_var: __workflow_loop_node_item
        label: "{{ __workflow_loop_item.name }}/{{ __workflow_loop_node_item.identifier }}"
        pause: "{{ controller_configuration_workflow_job_templates_loop_delay }}"
      async: "{{ ansible_check_mode | ternary(0, 1000) }}"
      poll: 0
      register: __workflows_node_async
      changed_when: not __workflows_node_async.changed

    - name: add_workflows_schema | Flag for errors (check mode only)
      ansible.builtin.set_fact:
        error_flag: true
      when: ansible_check_mode and __workflows_node_async.failed is defined and __workflows_node_async.failed

    - name: add_workflows_schema | Manage Workflows | Wait for finish the workflow creation
      when:
        - not ansible_check_mode
        - __workflows_node_async_results_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __workflows_node_async.results }}"
      loop_control:
        loop_var: __workflows_node_async_results_item
      vars:
        cas_secure_logging: "{{ controller_configuration_workflow_job_templates_secure_logging }}"
        cas_async_delay: "{{ controller_configuration_workflow_job_templates_async_delay }}"
        cas_async_retries: "{{ controller_configuration_workflow_job_templates_async_retries }}"
        cas_job_async_results_item: "{{ __workflows_node_async_results_item }}"
        cas_error_list_var_name: "controller_workflows_errors"

    # Create links between workflow node
    - name: add_workflows_schema | Create links between Workflow Nodes
      ansible.controller.workflow_job_template_node:
        identifier: "{{ __workflow_loop_node_item.identifier | mandatory }}"
        workflow: "{{ __workflow_loop_item.name | mandatory }}"
        always_nodes: "{{ __workflow_loop_node_item.always_nodes | default(__workflow_loop_node_item.related.always_nodes | default([], true) | selectattr('identifier',
          'defined') | map(attribute='identifier')) | list }}" # Nodes to advance on always (blue links)
        success_nodes: "{{ __workflow_loop_node_item.success_nodes | default(__workflow_loop_node_item.related.success_nodes | default([], true) | selectattr('identifier',
          'defined') | map(attribute='identifier')) | list }}" # Nodes to advance on success (green links)
        failure_nodes: "{{ __workflow_loop_node_item.failure_nodes | default(__workflow_loop_node_item.related.failure_nodes | default([], true) | selectattr('identifier',
          'defined') | map(attribute='identifier')) | list }}" # Nodes to advance on failure (red links)
        state: "{{ __workflow_loop_node_item.state | default(platform_state | default('present')) }}"
        organization: "{{ __workflow_loop_item.organization.name | default(__workflow_loop_item.organization) }}" # Workflow job template organization
        controller_username: "{{ aap_username | default(omit, true) }}"
        controller_password: "{{ aap_password | default(omit, true) }}"
        controller_oauthtoken: "{{ aap_token | default(omit, true) }}"
        request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
        controller_host: "{{ aap_hostname | default(omit, true) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
      loop: "{{ __workflow_loop_item.simplified_workflow_nodes }}"
      loop_control:
        loop_var: __workflow_loop_node_item
        label: "{{ __workflow_loop_node_item.identifier }}"
      # Execute only the nodes that define links to the following
      when: ((__workflow_loop_node_item.always_nodes is defined and __workflow_loop_node_item.always_nodes | length > 0) or (__workflow_loop_node_item.success_nodes is
        defined and __workflow_loop_node_item.success_nodes | length > 0) or (__workflow_loop_node_item.failure_nodes is defined and __workflow_loop_node_item.failure_nodes | length > 0))
      async: "{{ ansible_check_mode | ternary(0, 1000) }}"
      poll: 0
      register: __workflows_link_async

    - name: add_workflows_schema | Flag for errors (check mode only)
      ansible.builtin.set_fact:
        error_flag: true
      when:
        - ansible_check_mode
        - __workflows_link_async.failed is defined
        - __workflows_link_async.failed

    - name: add_workflows_schema | Manage Workflows | Wait for finish the workflow creation
      when:
        - not ansible_check_mode
        - __workflows_link_async_results_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __workflows_link_async.results }}"
      loop_control:
        loop_var: __workflows_link_async_results_item
      vars:
        cas_secure_logging: "{{ controller_configuration_workflow_job_templates_secure_logging }}"
        cas_async_delay: "{{ controller_configuration_workflow_job_templates_async_delay }}"
        cas_async_retries: "{{ controller_configuration_workflow_job_templates_async_retries }}"
        cas_job_async_results_item: "{{ __workflows_link_async_results_item }}"
        cas_error_list_var_name: "controller_workflows_errors"

  always:
    - name: add_workflows_schema | Cleanup async results files
      when:
        - not ansible_check_mode
        - __workflows_schema_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __workflows_schema_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __workflows_node_async.results + __workflows_link_async.results }}"
      loop_control:
        loop_var: __workflows_schema_results_item
        label: "Cleaning up job results file: {{ __workflows_schema_results_item.results_file | default('Unknown') }}"
...
