---
- name: Manage Service Keys Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ gateway_service_keys_secure_logging }}"
  block:
    - name: Service Keys | Configuration
      ansible.platform.service_key:
        name: "{{ __gateway_service_keys_item.name | mandatory }}"
        new_name: "{{ __gateway_service_keys_item.new_name | default(omit) }}"
        is_active: "{{ __gateway_service_keys_item.is_active | default(omit) }}"
        service_cluster: "{{ __gateway_service_keys_item.service_cluster | default(omit) }}"
        algorithm: "{{ __gateway_service_keys_item.algorithm | default(omit) }}"
        secret: "{{ __gateway_service_keys_item.secret | default(omit) }}"
        secret_length: "{{ __gateway_service_keys_item.secret_length | default(omit) }}"
        mark_previous_inactive: "{{ __gateway_service_keys_item.mark_previous_inactive | default(omit) }}"
        state: "{{ __gateway_service_keys_item.state | default(platform_state | default(omit, true)) }}"

        # Role Standard Options
        gateway_hostname: "{{ aap_hostname | default(omit, true) }}"
        gateway_username: "{{ aap_username | default(omit, true) }}"
        gateway_password: "{{ aap_password | default(omit, true) }}"
        gateway_token: "{{ aap_token | default(omit, true) }}"
        gateway_request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
        gateway_validate_certs: "{{ aap_validate_certs | default(omit) }}"
      loop: "{{ gateway_service_keys }}"
      loop_control:
        loop_var: __gateway_service_keys_item
        label: "{{ __operation.verb }} the Gateway service key {{ __gateway_service_keys_item.name }}"
        pause: "{{ gateway_service_keys_loop_delay }}"
      async: 1000
      poll: 0
      register: __gateway_service_keys_job_async
      changed_when: not __gateway_service_keys_job_async.changed
      vars:
        __operation: "{{ operation_translate[__gateway_service_keys_item.state | default(platform_state) | default('present')] }}"

    - name: Service Keys | Wait for finish the configuration
      when:
        - not ansible_check_mode
        - __gateway_service_keys_job_async_results_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __gateway_service_keys_job_async.results }}"
      loop_control:
        loop_var: __gateway_service_keys_job_async_results_item
        label: "{{ __operation.verb }} Gateway service key {{ __gateway_service_keys_job_async_results_item.__gateway_service_keys_item.name }} | Wait for finish the Gateway service key {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ gateway_service_keys_secure_logging }}"
        cas_async_delay: "{{ gateway_service_keys_async_delay }}"
        cas_async_retries: "{{ gateway_service_keys_async_retries }}"
        cas_job_async_results_item: "{{ __gateway_service_keys_job_async_results_item }}"
        cas_error_list_var_name: "gateway_service_keys_errors"
        __operation: "{{ operation_translate[__gateway_service_keys_job_async_results_item.__gateway_service_keys_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} Gateway service key {{ __gateway_service_keys_job_async_results_item.__gateway_service_keys_item.name }} | Wait for finish the Gateway service key {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __gateway_service_keys_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __gateway_service_keys_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __gateway_service_keys_job_async.results }}"
      loop_control:
        loop_var: __gateway_service_keys_job_async_results_item
        label: "Cleaning up job results file: {{ __gateway_service_keys_job_async_results_item.results_file | default('Unknown') }}"
...
