---
# Create EDA Controller Tokens
- name: Manage EDA Controller token Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ eda_configuration_users_token_secure_logging }}"
  block:
    - name: Add EDA Controller token
      ansible.eda.controller_token:
        name: "{{ __token_item.name }}"
        description: "{{ __token_item.description | default(omit) }}"
        token: "{{ __token_item.token | default(omit) }}"
        controller_host: "{{ aap_hostname | default(omit, true) }}"
        controller_username: "{{ aap_username | default(omit, true) }}"
        controller_password: "{{ aap_password | default(omit, true) }}"
        controller_token: "{{ aap_token | default(omit, true) }}"
        request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
      loop: "{{ eda_controller_tokens }}"
      loop_control:
        loop_var: __token_item
        label: "{{ __operation.verb }} the Controller token {{ __token_item.name }} to EDA"
        pause: "{{ eda_configuration_users_token_async_delay }}"
      async: 1000
      poll: 0
      register: __controller_tokens_job_async
      changed_when: not __controller_tokens_job_async.changed
      vars:
        __operation: "{{ operation_translate[__controller_tokens_job_async.state | default(platform_state) | default('present')] }}"

    - name: Create controller_token | Wait for finish the controller_token creation
      when:
        - not ansible_check_mode
        - __controller_tokens_job_async_result_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __controller_tokens_job_async.results }}"
      loop_control:
        loop_var: __controller_tokens_job_async_result_item
        label: "{{ __operation.verb }} Controller token {{ __controller_tokens_job_async_result_item.__token_item.name }} | Wait for finish the Controller token {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ eda_configuration_users_token_secure_logging }}"
        cas_async_delay: "{{ eda_configuration_users_token_async_delay }}"
        cas_async_retries: "{{ eda_configuration_users_token_async_retries }}"
        cas_job_async_results_item: "{{ __controller_tokens_job_async_result_item }}"
        cas_error_list_var_name: "eda_controller_tokens_errors"
        __operation: "{{ operation_translate[__controller_tokens_job_async_result_item.__token_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} Controller token {{ __controller_tokens_job_async_result_item.__token_item.name }} | Wait for finish the Controller token {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __controller_tokens_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __controller_tokens_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __controller_tokens_job_async.results }}"
      loop_control:
        loop_var: __controller_tokens_job_async_result_item
        label: "Cleaning up job results file: {{ __controller_tokens_job_async_result_item.results_file | default('Unknown') }}"
...
