---
# Sync AH repository
- name: Manage Hub Collection Repository Sync Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ hub_configuration_collection_repository_sync_secure_logging }}"
  block:
    - name: Sync Automation Hub Collection Remote repository
      ansible.hub.collection_repository_sync:
        name: "{{ __hub_collection_repository_sync_item.name }}"
        wait: "{{ __hub_collection_repository_sync_item.wait | default(omit) }}"
        interval: "{{ __hub_collection_repository_sync_item.interval | default(1) }}"
        timeout: "{{ __hub_collection_repository_sync_item.timeout | default(omit) }}"
        ah_host: "{{ aap_hostname | default(omit) }}"
        ah_username: "{{ aap_username | default(omit) }}"
        ah_password: "{{ aap_password | default(omit) }}"
        ah_path_prefix: "{{ hub_path_prefix | default(ah_path_prefix | default(omit)) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
        request_timeout: "{{ aap_request_timeout | default(omit) }}"
      loop: "{{ hub_collection_repositories }}"
      loop_control:
        loop_var: __hub_collection_repository_sync_item
        label: "{{ __operation.verb }} the sync {{ __hub_collection_repository_sync_item.name }} in Hub"
        pause: "{{ hub_configuration_collection_repository_sync_loop_delay }}"
      when: __hub_collection_repository_sync_item.sync | default(true)
      async: "{{ hub_configuration_collection_repository_sync_async_timeout }}"
      poll: 0
      register: __collection_repository_sync_job_async
      changed_when: not __collection_repository_sync_job_async.changed
      vars:
        __operation: "{{ operation_translate[__hub_collection_repository_sync_item.state | default(platform_state) | default('present')] }}"

    - name: Sync Repository | Wait for finish the repository sync
      when:
        - not ansible_check_mode
        - __collection_repository_sync_job_async_result_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __collection_repository_sync_job_async.results }}"
      loop_control:
        loop_var: __collection_repository_sync_job_async_result_item
        label: "{{ __operation.verb }} Collection repository sync {{ __collection_repository_sync_job_async_result_item.__hub_collection_repository_sync_item.name }}
          | Wait to finish the Repository sync"
      vars:
        cas_secure_logging: "{{ hub_configuration_collection_repository_sync_secure_logging }}"
        cas_async_delay: "{{ hub_configuration_collection_repository_sync_async_delay }}"
        cas_async_retries: "{{ hub_configuration_collection_repository_sync_async_retries }}"
        cas_job_async_results_item: "{{ __collection_repository_sync_job_async_result_item }}"
        cas_error_list_var_name: "hub_collection_repository_sync_errors"
        __operation: "{{ operation_translate[__collection_repository_sync_job_async_result_item.__hub_collection_repository_sync_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} Collection repository sync {{ __collection_repository_sync_job_async_result_item.__hub_collection_repository_sync_item.name }} | Wait to finish the Repository sync"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __collection_repository_sync_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __collection_repository_sync_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __collection_repository_sync_job_async.results }}"
      loop_control:
        loop_var: __collection_repository_sync_job_async_result_item
        label: "Cleaning up job results file: {{ __collection_repository_sync_job_async_result_item.results_file | default('Unknown') }}"
...
