---
- name: Manage Hub Publish Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ hub_configuration_publish_secure_logging }}"
  block:
    - name: Git checkout
      ansible.builtin.git:
        repo: "{{ __hub_collection_item.git_url }}"
        dest: "{{ aap_configuration_working_dir }}/{{ __hub_collection_item.collection_name }}"
        version: "{{ __hub_collection_item.version | default(omit) }}"
        key_file: "{{ __hub_collection_item.key_path | default(omit) }}"
        ssh_opts: "{{ __hub_collection_item.ssh_opts | default(omit) }}"
      loop: "{{ hub_custom_collections }}"
      loop_control:
        loop_var: __hub_collection_item
        pause: "{{ hub_configuration_publish_loop_delay }}"
      when:
        - hub_collection_list | length == 0
        - __hub_collection_item.collection_local_path is not defined

    - name: Copy local collection to working dir
      ansible.builtin.copy:
        src: "{{ __hub_collection_item.collection_local_path }}/"
        dest: "{{ aap_configuration_working_dir }}/{{ __hub_collection_item.collection_name }}"
        remote_src: true
        mode: "0700"
      loop: "{{ hub_collection_list }}"
      loop_control:
        loop_var: __hub_collection_item
      when:
        - hub_collection_list | length > 0
        - __hub_collection_item.collection_local_path is defined

    - name: Build Collections
      ansible.hub.ah_build:
        path: "{{ aap_configuration_working_dir }}/{{ __hub_collection_item.collection_name }}"
        output_path: "{{ aap_configuration_working_dir }}/{{ __hub_collection_item.collection_name }}"
        force: true
      register: __hub_build_results
      loop: "{{ hub_collection_list | default(hub_custom_collections, true) | select }}"
      loop_control:
        loop_var: __hub_collection_item

    - name: Find if variable contains file or dir
      ansible.builtin.stat:
        path: "{{ __hub_build_result_item.path }}"
      register: __hub_build_stat_results
      loop: "{{ __hub_build_results.results }}"
      loop_control:
        loop_var: __hub_build_result_item
      when: __hub_build_results is not skipped

    - name: Find all relevant built collection files
      ansible.builtin.find:
        paths: "{{ (__hub_build_result_item.stat.isdir) | ternary(__hub_build_result_item.stat.path, (__hub_build_result_item.stat.path | dirname)) }}"
        patterns: "{{ (__hub_build_result_item.stat.isdir) | ternary('*.tar.gz', (__hub_build_result_item.stat.path | basename)) }}"
      register: __hub_collections_find_results
      loop: "{{ __hub_build_stat_results.results }}"
      loop_control:
        loop_var: __hub_build_result_item
      when: __hub_build_results is not skipped

    - name: Set path for all collections found
      ansible.builtin.set_fact:
        __hub_collection_list: "{{ __hub_collections_find_results.results | map(attribute='files') | flatten | map(attribute='path') | flatten }}"
      when: __hub_build_results is not skipped

    - name: Get token
      ansible.hub.ah_token:
        ah_host: "{{ aap_hostname | default(omit) }}"
        ah_username: "{{ aap_username | default(omit) }}"
        ah_password: "{{ aap_password | default(omit) }}"
        ah_path_prefix: "{{ hub_path_prefix | default(ah_path_prefix | default(omit)) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
        request_timeout: "{{ aap_request_timeout | default(omit) }}"
      when:
        - hub_token is not defined
        - lookup("ansible.builtin.env", "AH_API_TOKEN") == ""
        - __hub_collection_list is defined

    - name: Publish Collections
      ansible.hub.ah_collection:
        namespace: "{{ (__hub_collection_file | basename).split('-')[0] }}"
        name: "{{ (__hub_collection_file | basename).split('-')[1] }}"
        version: "{{ (__hub_collection_file | basename).split('-')[2:] | join('-') | splitext | first | splitext | first }}"
        path: "{{ __hub_collection_file }}"
        auto_approve: "{{ hub_auto_approve }}"
        overwrite_existing: "{{ hub_overwrite_existing }}"
        ah_host: "{{ aap_hostname | default(omit) }}"
        ah_username: "{{ aap_username | default(omit) }}"
        ah_password: "{{ aap_password | default(omit) }}"
        ah_token: "{{ hub_token | default(omit) }}"
        ah_path_prefix: "{{ hub_path_prefix | default(ah_path_prefix | default(omit)) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
        request_timeout: "{{ aap_request_timeout | default(omit) }}"
      loop: "{{ __hub_collection_list }}"
      loop_control:
        loop_var: __hub_collection_file
      async: "{{ hub_configuration_publish_async_timeout }}"
      poll: 0
      register: __publish_job_async
      changed_when: not __publish_job_async.changed
      when: __hub_collection_list is defined

    - name: Publish Collection | Wait for finish the publish creation
      when:
        - not ansible_check_mode
        - __publish_job_async_result_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __publish_job_async.results }}"
      loop_control:
        loop_var: __publish_job_async_result_item
      vars:
        cas_secure_logging: "{{ hub_configuration_publish_secure_logging }}"
        cas_async_delay: "{{ hub_configuration_publish_async_delay }}"
        cas_async_retries: "{{ hub_configuration_publish_async_retries }}"
        cas_job_async_results_item: "{{ __publish_job_async_result_item }}"
        cas_error_list_var_name: "hub_publish_errors"
        cas_object_label: "Waiting for collection {{ (__publish_job_async_result_item.__hub_collection_file | basename).split('-')[1] }} to be published"

    - name: Approve Collections
      ansible.hub.ah_approval:
        namespace: "{{ (__hub_collection_file | basename).split('-')[0] }}"
        name: "{{ (__hub_collection_file | basename).split('-')[1] }}"
        version: "{{ (__hub_collection_file | basename).split('-')[2:] | join('-') | splitext | first | splitext | first }}"
        ah_host: "{{ aap_hostname | default(omit) }}"
        ah_username: "{{ aap_username | default(omit) }}"
        ah_password: "{{ aap_password | default(omit) }}"
        ah_token: "{{ hub_token | default(omit) }}"
        ah_path_prefix: "{{ hub_path_prefix | default(ah_path_prefix | default(omit)) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
        request_timeout: "{{ aap_request_timeout | default(omit) }}"
      loop: "{{ __hub_collection_list }}"
      loop_control:
        loop_var: __hub_collection_file
      when:
        - not hub_auto_approve
        - __hub_collection_list is defined
      register: approval
      retries: 3
      delay: 2
      until: not approval is failed

    - name: Cleanup working dir
      ansible.builtin.file:
        path: "{{ __hub_collection_item | dirname }}"
        state: absent
      loop: "{{ __hub_collection_list }}"
      loop_control:
        loop_var: __hub_collection_item
        label: "{{ __hub_collection_item | dirname }}"
      when: __hub_collection_list is defined

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __publish_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __publish_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __publish_job_async.results }}"
      loop_control:
        loop_var: __publish_job_async_result_item
        label: "Cleaning up job results file: {{ __publish_job_async_result_item.results_file | default('Unknown') }}"
...
