---
controller_credentials:
  - name: "SNOW"
    description: !unsafe ''
    credential_type: "ServiceNow"
    organization: "{{ customer_org_name }}"
    inputs:
      instance: "https://{{ snow_hostname }}"
      password: "{{ snow_password}}"
      username: admin
  - name: "Controller Credential"
    description: !unsafe ''
    credential_type: "Red Hat Ansible Automation Platform"
    organization: "Default"
    inputs:
      host: "{{ aap_hostname }}"
      password: "{{ aap_password }}"
      username: admin
  - name: "AWS"
    description: !unsafe ''
    credential_type: "Amazon Web Services"
    organization: "Default"
    inputs:
      password: "{{ aws_secret_key }}"
      username: "{{ aws_access_key }}"
  # - name: "Insights Inventory"
  #   description: !unsafe ''
  #   credential_type: "Insights Collection"
  #   organization: "Default"
  #   inputs:
  #     insights_user: REPLACEME
  #     insights_password: ''
  - name: "EC2 Machine"
    description: !unsafe ''
    credential_type: "Machine"
    organization: "Default"
    inputs:
      username: ec2-user
      ssh_key_data: "{{ ec2_ssh_private_key }}"

