---
eda_credentials:
#   - name: "Decision Environment Container Registry"
#     description: ""
#     credential_type:
#       name: Container Registry
#       namespace: registry
#       kind: registry
#     organization:
#       name: Default
#       description: The default organization for Ansible Automation Platform
#     references: ""
#     inputs:
#       host: registry.redhat.io
#       password: $encrypted$
#       username: fredmkson
#       verify_ssl: true
#   - name: "Hub Decision Environment Container Registry"
#     description: ""
#     credential_type:
#       name: Container Registry
#       namespace: registry
#       kind: registry
#     organization:
#       name: Default
#       description: The default organization for Ansible Automation Platform
#     references: ""
#     inputs:
#       host: ip-172-31-7-190.ap-southeast-2.compute.internal
#       password: $encrypted$
#       username: admin
#       verify_ssl: false
  - name: "AAP"
    description: "AAP credentials"
    credential_type: 'Red Hat Ansible Automation Platform'
    organization: Default
      # description: The default organization for Ansible Automation Platform
    inputs:
      host: "https://{{ aap_hostname }}/api/controller/"
      password: "{{ aap_password }}"
      # request_timeout: '10'
      username: "{{ aap_username }}"
      verify_ssl: false

