---
controller_inventory_sources:
  - name: "now"
    description: ''
    organization: "{{ customer_org_name }}"
    source: "scm"
    limit: ""
    source_project: "DevOps"
    source_path: "demo_snow/inventory.now.yaml"
    inventory: "SNOW"
    update_on_launch: "False"
    overwrite: "True"
    credential: "SNOW"
    source_vars: "{}"
    host_filter: "{{ customer_org_name | lower }}-"
