---
- name: Manage Gateway Users Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ gateway_users_secure_logging }}"
  block:
    - name: Users | Configuration
      ansible.platform.user:
        username: "{{ __gateway_user_accounts_item.username | mandatory }}"
        # the 'true' in the second default leads to no password being set if the default password is empty
        password: "{{ __gateway_user_accounts_item.password | default(users_default_password | default(omit, true)) }}"
        email: "{{ __gateway_user_accounts_item.email | default(omit, true) }}"
        first_name: "{{ __gateway_user_accounts_item.first_name | default(omit, true) }}"
        last_name: "{{ __gateway_user_accounts_item.last_name | default(omit, true) }}"
        is_superuser: "{{ __gateway_user_accounts_item.is_superuser | default(omit) }}"
        update_secrets: "{{ __gateway_user_accounts_item.update_secrets | default(omit) }}"
        organizations: "{{ __gateway_user_accounts_item.organizations | default(omit) }}"
        authenticators: "{{ __gateway_user_accounts_item.authenticators | default(omit) }}"
        authenticator_uid: "{{ __gateway_user_accounts_item.authenticator_uid | default(omit) }}"
        state: "{{ __gateway_user_accounts_item.state | default(platform_state | default(omit, true)) }}"

        # Role Standard Options
        gateway_hostname: "{{ aap_hostname | default(omit, true) }}"
        gateway_username: "{{ aap_username | default(omit, true) }}"
        gateway_password: "{{ aap_password | default(omit, true) }}"
        gateway_token: "{{ aap_token | default(omit, true) }}"
        gateway_request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
        gateway_validate_certs: "{{ aap_validate_certs | default(omit) }}"
      loop: "{{ aap_user_accounts }}"
      loop_control:
        loop_var: __gateway_user_accounts_item
        label: "{{ __operation.verb }} the Gateway user {{ __gateway_user_accounts_item.username }}"
        pause: "{{ gateway_users_loop_delay }}"
      async: 1000
      poll: 0
      register: __gateway_user_accounts_job_async
      changed_when: not __gateway_user_accounts_job_async.changed
      vars:
        __operation: "{{ operation_translate[__gateway_user_accounts_item.state | default(platform_state) | default('present')] }}"

    - name: Users | Wait for finish the configuration
      when:
        - not ansible_check_mode
        - __gateway_user_accounts_job_async_results_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __gateway_user_accounts_job_async.results }}"
      loop_control:
        loop_var: __gateway_user_accounts_job_async_results_item
        label: "{{ __operation.verb }} Gateway user {{ __gateway_user_accounts_job_async_results_item.__gateway_user_accounts_item.username }} | Wait for finish the Gateway user {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ gateway_users_secure_logging }}"
        cas_async_delay: "{{ gateway_users_async_delay }}"
        cas_async_retries: "{{ gateway_users_async_retries }}"
        cas_job_async_results_item: "{{ __gateway_user_accounts_job_async_results_item }}"
        cas_error_list_var_name: "gateway_users_errors"
        __operation: "{{ operation_translate[__gateway_user_accounts_job_async_results_item.__gateway_user_accounts_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} Gateway user {{ __gateway_user_accounts_job_async_results_item.__gateway_user_accounts_item.username }} | Wait for finish the Gateway user {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __gateway_user_accounts_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __gateway_user_accounts_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __gateway_user_accounts_job_async.results }}"
      loop_control:
        loop_var: __gateway_user_accounts_job_async_results_item
        label: "Cleaning up job results file: {{ __gateway_user_accounts_job_async_results_item.results_file | default('Unknown') }}"
...
