---
- name: Manage Gateway Authenticator Map Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ gateway_authenticator_maps_secure_logging }}"
  block:
    - name: Authenticator Map | Configuration
      ansible.platform.authenticator_map:
        name: "{{ __gateway_authenticator_maps_item.name | mandatory }}"
        new_name: "{{ __gateway_authenticator_maps_item.new_name | default(omit) }}"
        authenticator: "{{ __gateway_authenticator_maps_item.authenticator | default(omit) }}"
        new_authenticator: "{{ __gateway_authenticator_maps_item.new_authenticator | default(omit) }}"
        revoke: "{{ __gateway_authenticator_maps_item.revoke | default(omit) }}"
        map_type: "{{ __gateway_authenticator_maps_item.map_type | default(omit) }}"
        team: "{{ __gateway_authenticator_maps_item.team | default(omit) }}"
        organization: "{{ __gateway_authenticator_maps_item.organization | default(omit) }}"
        role: "{{ __gateway_authenticator_maps_item.role | default(omit) }}"
        triggers: "{{ __gateway_authenticator_maps_item.triggers | default(omit) }}"
        order: "{{ __gateway_authenticator_maps_item.order | default(omit) }}"
        state: "{{ __gateway_authenticator_maps_item.state | default(platform_state | default(omit, true)) }}"

        # Role Standard Options
        gateway_hostname: "{{ aap_hostname | default(omit, true) }}"
        gateway_username: "{{ aap_username | default(omit, true) }}"
        gateway_password: "{{ aap_password | default(omit, true) }}"
        gateway_token: "{{ aap_token | default(omit, true) }}"
        gateway_request_timeout: "{{ aap_request_timeout | default(omit, true) }}"
        gateway_validate_certs: "{{ aap_validate_certs | default(omit) }}"
      loop: "{{ gateway_authenticator_maps }}"
      loop_control:
        loop_var: __gateway_authenticator_maps_item
        label: "{{ __operation.verb }} AAP Platform Authenticator Maps {{ __gateway_authenticator_maps_item.name }}"
        pause: "{{ gateway_authenticator_maps_loop_delay }}"
      async: 1000
      poll: 0
      register: __gateway_authenticator_maps_job_async
      changed_when: not __gateway_authenticator_maps_job_async.changed
      vars:
        __operation: "{{ operation_translate[__gateway_authenticator_maps_item.state | default(platform_state) | default('present')] }}"

    - name: Authenticator Map | Wait for finish the configuration
      when:
        - not ansible_check_mode
        - __gateway_authenticator_maps_job_async_results_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __gateway_authenticator_maps_job_async.results }}"
      loop_control:
        loop_var: __gateway_authenticator_maps_job_async_results_item
        label: "{{ __operation.verb }} AAP Platform Authenticator Maps {{ __gateway_authenticator_maps_job_async_results_item.__gateway_authenticator_maps_item.name }}
          | Wait for finish the Authenticator Map {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ gateway_authenticator_maps_secure_logging }}"
        cas_async_delay: "{{ gateway_authenticator_maps_async_delay }}"
        cas_async_retries: "{{ gateway_authenticator_maps_async_retries }}"
        cas_job_async_results_item: "{{ __gateway_authenticator_maps_job_async_results_item }}"
        cas_error_list_var_name: "gateway_authenticator_maps_errors"
        __operation: "{{ operation_translate[__gateway_authenticator_maps_job_async_results_item.__gateway_authenticator_maps_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} AAP Platform Authenticator Maps {{ __gateway_authenticator_maps_job_async_results_item.__gateway_authenticator_maps_item.name }} | Wait for finish the Authenticator Map {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __gateway_authenticator_maps_job_async_results_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __gateway_authenticator_maps_job_async_results_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __gateway_authenticator_maps_job_async.results }}"
      loop_control:
        loop_var: __gateway_authenticator_maps_job_async_results_item
        label: "Cleaning up job results file: {{ __gateway_authenticator_maps_job_async_results_item.results_file | default('Unknown') }}"
...
