---
# Create AH EE registry
- name: Manage Hub EE Registry Block
  vars:
    ansible_async_dir: "{{ aap_configuration_async_dir }}"
  no_log: "{{ hub_configuration_ee_registry_secure_logging }}"
  block:
    - name: Add Automation Hub EE Registry
      ansible.hub.ah_ee_registry:
        name: "{{ __hub_ee_registry_item.name }}"
        url: "{{ __hub_ee_registry_item.url }}"
        username: "{{ __hub_ee_registry_item.username | default(omit) }}"
        password: "{{ __hub_ee_registry_item.password | default(omit) }}"
        tls_validation: "{{ __hub_ee_registry_item.tls_validation | default(omit) }}"
        download_concurrency: "{{ __hub_ee_registry_item.download_concurrency | default(omit) }}"
        rate_limit: "{{ __hub_ee_registry_item.rate_limit | default(omit) }}"
        state: "{{ __hub_ee_registry_item.state | default(hub_state | default(ah_state | default('present'))) }}"
        ah_host: "{{ aap_hostname | default(omit) }}"
        ah_username: "{{ aap_username | default(omit) }}"
        ah_password: "{{ aap_password | default(omit) }}"
        ah_path_prefix: "{{ hub_path_prefix | default(ah_path_prefix | default(omit)) }}"
        validate_certs: "{{ aap_validate_certs | default(omit) }}"
        request_timeout: "{{ aap_request_timeout | default(omit) }}"
        proxy_url: "{{ __hub_ee_registry_item.proxy_url | default(proxy_url | default(omit)) }}"
        proxy_username: "{{ __hub_ee_registry_item.proxy_username | default(proxy_username | default(omit)) }}"
        proxy_password: "{{ __hub_ee_registry_item.proxy_password | default(proxy_password | default(omit)) }}"
      loop: "{{ hub_ee_registries }}"
      loop_control:
        loop_var: __hub_ee_registry_item
        label: "{{ __operation.verb }} the EE registry {{ __hub_ee_registry_item.name }} in Hub"
        pause: "{{ hub_configuration_ee_registry_loop_delay }}"
      async: "{{ hub_configuration_ee_registry_async_timeout }}"
      poll: 0
      register: __ee_registries_job_async
      changed_when: not __ee_registries_job_async.changed
      vars:
        __operation: "{{ operation_translate[__hub_ee_registry_item.state | default(platform_state) | default('present')] }}"

    - name: Create EE Registry | Wait for finish the ee_registry creation
      when:
        - not ansible_check_mode
        - __ee_registries_job_async_result_item.ansible_job_id is defined
      ansible.builtin.include_role:
        name: infra.aap_configuration.collect_async_status
      loop: "{{ __ee_registries_job_async.results }}"
      loop_control:
        loop_var: __ee_registries_job_async_result_item
        label: "{{ __operation.verb }} EE Registry {{ __ee_registries_job_async_result_item.__hub_ee_registry_item.name }} | Wait for finish the EE Registry {{ __operation.action }}"
      vars:
        cas_secure_logging: "{{ hub_configuration_ee_registry_secure_logging }}"
        cas_async_delay: "{{ hub_configuration_ee_registry_async_delay }}"
        cas_async_retries: "{{ hub_configuration_ee_registry_async_retries }}"
        cas_job_async_results_item: "{{ __ee_registries_job_async_result_item }}"
        cas_error_list_var_name: "hub_ee_registry_errors"
        __operation: "{{ operation_translate[__ee_registries_job_async_result_item.__hub_ee_registry_item.state | default(platform_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} EE Registry {{ __ee_registries_job_async_result_item.__hub_ee_registry_item.name }} | Wait for finish the EE Registry {{ __operation.action }}"

  always:
    - name: Cleanup async results files
      when:
        - not ansible_check_mode
        - __ee_registries_job_async_result_item.ansible_job_id is defined
      ansible.builtin.async_status:
        jid: "{{ __ee_registries_job_async_result_item.ansible_job_id }}"
        mode: cleanup
      loop: "{{ __ee_registries_job_async.results }}"
      loop_control:
        loop_var: __ee_registries_job_async_result_item
        label: "Cleaning up job results file: {{ __ee_registries_job_async_result_item.results_file | default('Unknown') }}"
...
